package pojo;
// Generated Oct 26, 2020 7:55:38 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import DAO.PengirimanDAO;

@ManagedBean

/**
 * Pengiriman generated by hbm2java
 */
public class Pengiriman  implements java.io.Serializable {


     private Integer id;
     private String nama;
     private String alamat;
     private String kota;
     private String provinsi;
     private int kodePos;
     private String noTelp;

    public Pengiriman() {
    }

    public Pengiriman(String nama, String alamat, String kota, String provinsi, int kodePos, String noTelp) {
       this.nama = nama;
       this.alamat = alamat;
       this.kota = kota;
       this.provinsi = provinsi;
       this.kodePos = kodePos;
       this.noTelp = noTelp;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getKota() {
        return this.kota;
    }
    
    public void setKota(String kota) {
        this.kota = kota;
    }
    public String getProvinsi() {
        return this.provinsi;
    }
    
    public void setProvinsi(String provinsi) {
        this.provinsi = provinsi;
    }
    public int getKodePos() {
        return this.kodePos;
    }
    
    public void setKodePos(int kodePos) {
        this.kodePos = kodePos;
    }
    public String getNoTelp() {
        return this.noTelp;
    }
    
    public void setNoTelp(String noTelp) {
        this.noTelp = noTelp;
    }

    public List<Pengiriman> getAllRecords(){
        List<Pengiriman> pList = new ArrayList<Pengiriman>();
        PengirimanDAO peng = new PengirimanDAO();
        pList = peng.getAll();
        return pList;
    }
    
    public void add(){
        PengirimanDAO add = new PengirimanDAO();
        add.add(this);
    }
    
    public void getById(){
        PengirimanDAO peng = new PengirimanDAO();
        List<Pengiriman> pList = peng.getById(id);
        nama = pList.get(0).nama;
        alamat = pList.get(0).alamat;
        kota = pList.get(0).kota;
        provinsi = pList.get(0).provinsi;
        kodePos = pList.get(0).kodePos;
        noTelp = pList.get(0).noTelp;       
    }
    
    public String getPengirimanName(Integer id){
        PengirimanDAO peng = new PengirimanDAO();
        List<Pengiriman> pList = peng.getById(id);
        nama = pList.get(0).nama;
        return nama;
    }
    
    public String edit(){
        PengirimanDAO peng = new PengirimanDAO();
        peng.edit(this);
        nama = "";
        alamat = "";
        kota = "";
        provinsi = "";
        kodePos = kodePos;
        noTelp = "";
        FacesMessage facesMessages = new FacesMessage(FacesMessage.SEVERITY_INFO,"Berhasil Edit Data",null);
        return "pengiriman";
    }
    
    public String delete(){
        PengirimanDAO peng = new PengirimanDAO();
        peng.delete(id);
        nama = "";
        alamat = "";
        kota = "";
        provinsi = "";
        kodePos = kodePos;
        noTelp = "";
        return "pengiriman";
    }
    
    public String home(){
        return "pengiriman";
    }
    
    public String crud(){
        return "pengiriman_edit";
    }
}


