package pojo;
// Generated Oct 26, 2020 7:55:38 PM by Hibernate Tools 4.3.1

import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import DAO.ProdukDAO;
import java.util.ArrayList;


@ManagedBean

/**
 * Produk generated by hbm2java
 */
public class Produk  implements java.io.Serializable {


     private Integer id;
     private String judul;
     private String penggarang;
     private String penerbit;
     private String kategori;
     private int stock;
     private int received;
     private int shipped;

    public Produk() {
    }

    public Produk(String judul, String penggarang, String penerbit, String kategori, int stock, int received, int shipped) {
       this.judul = judul;
       this.penggarang = penggarang;
       this.penerbit = penerbit;
       this.kategori = kategori;
       this.stock = stock;
       this.received = received;
       this.shipped = shipped;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getJudul() {
        return this.judul;
    }
    
    public void setJudul(String judul) {
        this.judul = judul;
    }
    public String getPenggarang() {
        return this.penggarang;
    }
    
    public void setPenggarang(String penggarang) {
        this.penggarang = penggarang;
    }
    public String getPenerbit() {
        return this.penerbit;
    }
    
    public void setPenerbit(String penerbit) {
        this.penerbit = penerbit;
    }
    public String getKategori() {
        return this.kategori;
    }
    
    public void setKategori(String kategori) {
        this.kategori = kategori;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public int getReceived() {
        return this.received;
    }
    
    public void setReceived(int received) {
        this.received = received;
    }
    public int getShipped() {
        return this.shipped;
    }
    
    public void setShipped(int shipped) {
        this.shipped = shipped;
    }

    public List<Produk> getAllRecords(){
    List<Produk> prodList = new ArrayList<Produk>();
    ProdukDAO prod = new ProdukDAO();
    return prodList;
    }
    
    public void save(){
        ProdukDAO add = new ProdukDAO();
        add.add(this);
    }
    
    public void getById(){
        ProdukDAO prod = new ProdukDAO();
        List<Produk> productList = prod.getById(id);
        judul = productList.get(0).judul;
        penggarang = productList.get(0).penggarang;
        penerbit = productList.get(0).penerbit;
        kategori = productList.get(0).kategori;
        stock = productList.get(0).stock;
        received = productList.get(0).received;
        shipped = productList.get(0).shipped;
    }
    public String getProdukName(Integer id){
        ProdukDAO produk = new ProdukDAO();
        List<Produk> productList = produk.getById(id);
        judul = productList.get(0).judul;
        return judul;
    }
    
    public void edit(){
        ProdukDAO prod = new ProdukDAO();
        prod.edit(this);
        judul = "";
        penggarang = "";
        penerbit = "";
        kategori = "";
        stock = stock;
        received = received;
        shipped = shipped;
        FacesMessage facesMessages = new FacesMessage(FacesMessage.SEVERITY_INFO,"Berhasil Edit Data",null);
    }
    
    public void delete(){
        ProdukDAO prod = new ProdukDAO();
        prod.delete(id);
        judul = "";
        penggarang = "";
        penerbit = "";
        kategori = "";
        stock = stock;
        received = received;
        shipped = shipped;
    }
    
    public String home(){
        return "produk";
    }
    
    public String crud(){
        return "produkedit";
    }
}


